name: Quire

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  quire-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install Quire CLI
        run: sudo npm install --global @thegetty/quire-cli@1.0.0-rc.11

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "githubaction@users.noreply.github.com"

      - name: Set publication URL
        run: |
          sed -i 's@^url:.*$@url: https://${PUBLIC_URL}@' content/_data/publication.yaml
          grep 'url:' content/_data/publication.yaml
        env:
          PUBLIC_URL: ${{ vars.PUBLIC_URL }}

      - name: Build site
        run: quire build

      - name: Replace docs with fresh build
        run: |
          rm -rf docs
          mv _site docs
          touch docs/.nojekyll

      - name: Commit generated site
        run: |
          git add docs
          git diff --cached --quiet || git commit -m "Quire: publishing assets"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
